name: Rust

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Run tests
        run: cargo test

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v7
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: rust
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4
      - name: Analyze
        uses: github/codeql-action/analyze@v4

  cargo-build:
    name: Cargo Build (${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs:
      - test
      - codeql
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
          - arch: aarch64-unknown-linux-gnu
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v7
      - name: Install cross tool
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build debug
        if: github.event_name == 'pull_request'
        run: cross build --target "${{ matrix.target }}"
      - name: Build release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: cross build --target "${{ matrix.target }}" --release
